apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 81.5.0 # Recommended: Check for the latest version
    helm:
      valueFiles:
      - $values/nucky-thompson/gitops/infra/values/kube-prometheus-stack.yaml
  - repoURL:  https://github.com/BeatGrate/homelab.git
    targetRevision: initial-test
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true # Allows ArgoCD to delete resources that are no longer in Git
      selfHeal: true # Allows ArgoCD to sync changes if the live state drifts from Git
    syncOptions:
      # Automatically create the destination namespace if it doesn't exist
      - CreateNamespace=true

