apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prom-alert-manager
  namespace: monitoring
spec:
  defaultBackend:
    service:
      name: kube-prometheus-kube-prome-alertmanager
      port:
        number: 9093
  ingressClassName: tailscale
  tls:
    - hosts:
        - alertmanager
